# Generated by Django 4.2.7 on 2026-05-13 23:23

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('store_number', models.CharField(max_length=10, unique=True)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('vision', models.TextField(blank=True)),
                ('mission', models.TextField(blank=True)),
                ('timezone_name', models.CharField(default='America/Chicago', help_text='IANA timezone identifier; used to render local dates.', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='english', max_length=10)),
                ('theme_color', models.CharField(default='#E51636', max_length=7)),
                ('dark_mode', models.BooleanField(default=False)),
                ('compact_mode', models.BooleanField(default=False)),
                ('notifications', models.JSONField(default=api.models._default_notification_prefs)),
                ('quick_action_ids', models.JSONField(default=api.models._default_quick_action_ids)),
                ('insight_ids', models.JSONField(default=api.models._default_insight_ids)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.JSONField(default=api.models._default_feature_flags)),
                ('access', models.JSONField(default=api.models._default_access_toggles)),
                ('cleaning_settings', models.JSONField(default=api.models._default_cleaning_settings)),
                ('foh_require_initials', models.BooleanField(default=False, help_text='If true, FOH task completions require initials.')),
                ('waste_goal_daily', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('waste_goal_weekly', models.DecimalField(decimal_places=2, default=600, max_digits=10)),
                ('waste_goal_monthly', models.DecimalField(decimal_places=2, default=2500, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='api.store')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='api.store'),
        ),
    ]
