# Generated by Django 4.2.7 on 2026-05-13 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_backfill_stores'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('win', 'Win'), ('challenge', 'Challenge')], max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_tags', to='api.store')),
            ],
            options={
                'ordering': ['kind', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ShiftSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField()),
                ('shift_type', models.CharField(choices=[('opening', 'Opening'), ('mid', 'Mid'), ('closing', 'Closing')], max_length=20)),
                ('shift_status', models.CharField(choices=[('normal', 'Normal'), ('busy', 'Busy'), ('slow', 'Slow'), ('incident', 'Incident')], default='normal', max_length=20)),
                ('rating', models.PositiveSmallIntegerField(default=3, help_text='1-5 star rating of the shift.')),
                ('recap', models.TextField(blank=True)),
                ('sales_note', models.CharField(blank=True, max_length=200)),
                ('labor_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sos_note', models.CharField(blank=True, max_length=200)),
                ('handoff_note', models.TextField(blank=True)),
                ('needs_follow_up', models.BooleanField(default=False)),
                ('is_draft', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('shift_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_summaries_led', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_summaries', to='api.store')),
                ('tags', models.ManyToManyField(blank=True, related_name='summaries', to='api.shifttag')),
            ],
            options={
                'ordering': ['-shift_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FOHTaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('opening', 'Opening'), ('transition', 'Transition'), ('closing', 'Closing')], max_length=20)),
                ('text', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foh_task_templates', to='api.store')),
            ],
            options={
                'ordering': ['shift', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FOHTaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The shift date this completion applies to (local TZ).')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('initials', models.CharField(blank=True, max_length=4)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foh_completions', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='api.fohtasktemplate')),
            ],
        ),
        migrations.AddConstraint(
            model_name='shifttag',
            constraint=models.UniqueConstraint(fields=('store', 'kind', 'label'), name='unique_shift_tag_per_store'),
        ),
        migrations.AddIndex(
            model_name='shiftsummary',
            index=models.Index(fields=['store', 'shift_date'], name='api_shiftsu_store_i_bdf960_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftsummary',
            index=models.Index(fields=['store', 'is_draft'], name='api_shiftsu_store_i_7b7dfc_idx'),
        ),
        migrations.AddIndex(
            model_name='fohtasktemplate',
            index=models.Index(fields=['store', 'shift'], name='api_fohtask_store_i_4033ea_idx'),
        ),
        migrations.AddIndex(
            model_name='fohtaskcompletion',
            index=models.Index(fields=['date'], name='api_fohtask_date_0d59b8_idx'),
        ),
        migrations.AddConstraint(
            model_name='fohtaskcompletion',
            constraint=models.UniqueConstraint(fields=('template', 'date'), name='unique_foh_completion_per_day'),
        ),
    ]
