# Generated by Django 4.2.7 on 2026-05-14 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_shifttag_shiftsummary_fohtasktemplate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetupSheetShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('view', 'View'), ('edit', 'Edit')], default='view', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SetupSheetTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TimeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('positions_needed', models.JSONField(blank=True, default=list, help_text='List of {role, count} pairs.')),
                ('notes', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='setupsheet',
            options={'ordering': ['-updated_at', '-id']},
        ),
        migrations.AddField(
            model_name='setupsheet',
            name='areas_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='setupsheet',
            name='employees_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='setupsheet',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='setupsheet',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='setupsheet',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_setup_sheets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='setupsheet',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='setupsheet',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setup_sheets', to='api.store'),
        ),
        migrations.AddField(
            model_name='setupsheet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='setupsheet',
            name='week_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setupsheet',
            name='week_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='setupsheet',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_setup_sheets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='setupsheet',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.department'),
        ),
        migrations.AlterField(
            model_name='setupsheet',
            name='schedule_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='setupsheet',
            name='shift_type',
            field=models.CharField(blank=True, choices=[('opening', 'Opening'), ('closing', 'Closing'), ('mid', 'Mid')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='setupsheet',
            index=models.Index(fields=['store', 'status'], name='api_setupsh_store_i_65e763_idx'),
        ),
        migrations.AddIndex(
            model_name='setupsheet',
            index=models.Index(fields=['store', 'week_start'], name='api_setupsh_store_i_99eea9_idx'),
        ),
        migrations.AddField(
            model_name='timeblock',
            name='sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_blocks', to='api.setupsheet'),
        ),
        migrations.AddField(
            model_name='timeblock',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_blocks', to='api.setupsheettemplate'),
        ),
        migrations.AddField(
            model_name='setupsheettemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_setup_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='setupsheettemplate',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setup_sheet_templates', to='api.store'),
        ),
        migrations.AddField(
            model_name='setupsheetshare',
            name='shared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setup_sheets_shared_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='setupsheetshare',
            name='shared_with',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_setup_sheets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='setupsheetshare',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='api.setupsheet'),
        ),
        migrations.AddField(
            model_name='setupsheet',
            name='source_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_sheets', to='api.setupsheettemplate'),
        ),
        migrations.AddIndex(
            model_name='setupsheettemplate',
            index=models.Index(fields=['store'], name='api_setupsh_store_i_2da90f_idx'),
        ),
        migrations.AddConstraint(
            model_name='setupsheetshare',
            constraint=models.UniqueConstraint(fields=('sheet', 'shared_with'), name='unique_share_per_user'),
        ),
    ]
