# Generated by Django 4.2.7 on 2026-05-14 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_setupsheetshare_setupsheettemplate_timeblock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('foh', 'Front of House'), ('kitchen', 'Kitchen')], default='foh', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='daily', max_length=20)),
                ('days', models.JSONField(blank=True, default=list)),
                ('supplies', models.JSONField(blank=True, default=list, help_text="List of supply names, e.g. ['Sanitizer', 'Microfiber'].")),
                ('links', models.JSONField(blank=True, default=list, help_text='List of {label, url} objects.')),
                ('estimated_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_tasks', to='api.store')),
            ],
            options={
                'ordering': ['scope', 'frequency', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CleaningCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaning_completions', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='api.cleaningtask')),
            ],
        ),
        migrations.AddIndex(
            model_name='cleaningtask',
            index=models.Index(fields=['store', 'scope', 'frequency'], name='api_cleanin_store_i_fcfad6_idx'),
        ),
        migrations.AddIndex(
            model_name='cleaningcompletion',
            index=models.Index(fields=['date'], name='api_cleanin_date_484897_idx'),
        ),
        migrations.AddConstraint(
            model_name='cleaningcompletion',
            constraint=models.UniqueConstraint(fields=('task', 'date'), name='unique_cleaning_completion_per_day'),
        ),
    ]
