# Generated by Django 4.2.7 on 2026-05-14 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_cleaningtask_cleaningcompletion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=20, unique=True)),
                ('label', models.CharField(max_length=40)),
                ('emoji', models.CharField(blank=True, max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('emoji', models.CharField(blank=True, max_length=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('order', models.PositiveIntegerField(default=0)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meal_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.mealperiod')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='api.store')),
            ],
            options={
                'ordering': ['meal_period', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WasteReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=30)),
                ('label', models.CharField(max_length=60)),
                ('emoji', models.CharField(blank=True, max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_reasons', to='api.store')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WasteEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('unit', models.CharField(choices=[('pieces', 'Pieces'), ('portions', 'Portions')], default='pieces', max_length=20)),
                ('unit_price_at_time', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waste_entries', to='api.menuitem')),
                ('reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='api.wastereason')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_entries_logged', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_entries', to='api.store')),
            ],
            options={
                'ordering': ['-recorded_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='KitchenChecklistTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('opening', 'Opening'), ('transition', 'Transition'), ('closing', 'Closing')], max_length=20)),
                ('text', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_checklist_tasks', to='api.store')),
            ],
            options={
                'ordering': ['shift', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='KitchenChecklistCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kitchen_checklist_completions', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='api.kitchenchecklisttask')),
            ],
        ),
        migrations.AddConstraint(
            model_name='wastereason',
            constraint=models.UniqueConstraint(fields=('store', 'slug'), name='unique_waste_reason_per_store'),
        ),
        migrations.AddIndex(
            model_name='wasteentry',
            index=models.Index(fields=['store', 'recorded_at'], name='api_wasteen_store_i_27ef37_idx'),
        ),
        migrations.AddIndex(
            model_name='wasteentry',
            index=models.Index(fields=['store', 'menu_item'], name='api_wasteen_store_i_8d8e66_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['store', 'meal_period'], name='api_menuite_store_i_689c90_idx'),
        ),
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.UniqueConstraint(fields=('store', 'meal_period', 'name'), name='unique_menu_item_per_meal'),
        ),
        migrations.AddIndex(
            model_name='kitchenchecklisttask',
            index=models.Index(fields=['store', 'shift'], name='api_kitchen_store_i_fa9228_idx'),
        ),
        migrations.AddIndex(
            model_name='kitchenchecklistcompletion',
            index=models.Index(fields=['date'], name='api_kitchen_date_d87861_idx'),
        ),
        migrations.AddConstraint(
            model_name='kitchenchecklistcompletion',
            constraint=models.UniqueConstraint(fields=('template', 'date'), name='unique_kitchen_completion_per_day'),
        ),
    ]
