# Generated by Django 4.2.7 on 2026-05-14 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_mealperiod_menuitem_wastereason_wasteentry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('needs_attention', 'Needs Attention'), ('down', 'Down')], default='ok', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('installed_at', models.DateField(blank=True, null=True)),
                ('warranty_expires', models.DateField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TemperatureTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('equipment', 'Equipment'), ('product', 'Product')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('expected_min', models.DecimalField(decimal_places=2, help_text='Acceptable lower bound in °F.', max_digits=6)),
                ('expected_max', models.DecimalField(decimal_places=2, help_text='Acceptable upper bound in °F.', max_digits=6)),
                ('order', models.PositiveIntegerField(default=0)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperature_targets', to='api.store')),
            ],
            options={
                'ordering': ['kind', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TemperatureReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('unit', models.CharField(default='F', max_length=2)),
                ('status', models.CharField(choices=[('good', 'Good'), ('warning', 'Warning'), ('critical', 'Critical')], default='good', max_length=20)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temperature_readings', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='api.temperaturetarget')),
            ],
            options={
                'ordering': ['-recorded_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('cadence', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='weekly', max_length=20)),
                ('next_due', models.DateField(blank=True, null=True)),
                ('last_completed', models.DateField(blank=True, null=True)),
                ('urgency_threshold_days', models.PositiveIntegerField(default=3, help_text="Days before next_due to flag as 'Soon'. Past due → 'Overdue'.")),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api.equipment')),
            ],
            options={
                'ordering': ['next_due', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('history', 'History'), ('maintenance', 'Maintenance'), ('cleaning', 'Cleaning'), ('issue', 'Issue')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.equipment')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-performed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FoodSafetyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daypart', models.CharField(choices=[('morning', 'Morning'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=20)),
                ('text', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_safety_tasks', to='api.store')),
            ],
            options={
                'ordering': ['daypart', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FoodSafetyCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_safety_completions', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='api.foodsafetytask')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=30)),
                ('label', models.CharField(max_length=60)),
                ('emoji', models.CharField(blank=True, max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_categories', to='api.store')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_items', to='api.equipmentcategory'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='api.store'),
        ),
        migrations.AddIndex(
            model_name='temperaturetarget',
            index=models.Index(fields=['store', 'kind'], name='api_tempera_store_i_64dba2_idx'),
        ),
        migrations.AddIndex(
            model_name='temperaturereading',
            index=models.Index(fields=['target', 'recorded_at'], name='api_tempera_target__464940_idx'),
        ),
        migrations.AddIndex(
            model_name='foodsafetytask',
            index=models.Index(fields=['store', 'daypart'], name='api_foodsaf_store_i_639b90_idx'),
        ),
        migrations.AddConstraint(
            model_name='foodsafetycompletion',
            constraint=models.UniqueConstraint(fields=('template', 'date'), name='unique_food_safety_completion_per_day'),
        ),
        migrations.AddConstraint(
            model_name='equipmentcategory',
            constraint=models.UniqueConstraint(fields=('store', 'slug'), name='unique_equipment_category_per_store'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['store', 'category'], name='api_equipme_store_i_534ef2_idx'),
        ),
    ]
