# Generated by Django 4.2.7 on 2026-05-15 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_cleaningtask_area_description_assignee"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDevelopmentPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan_key",
                    models.CharField(
                        help_text="Slug identifier like 'heart-of-leadership', 'path-to-director'.",
                        max_length=80,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("completed", "Completed")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("current_step", models.PositiveIntegerField(default=0)),
                ("total_steps", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="development_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="userdevelopmentplan",
            constraint=models.UniqueConstraint(
                fields=("user", "plan_key"), name="unique_dev_plan_per_user"
            ),
        ),
    ]
