# Generated by Django 4.2.7 on 2026-05-15 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_user_development_plan"),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lesson_key",
                    models.CharField(
                        help_text="Slug or index identifier for the lesson, e.g. '01', 'week-1-introduction'.",
                        max_length=80,
                    ),
                ),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_completions",
                        to="api.userdevelopmentplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-completed_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="lessoncompletion",
            constraint=models.UniqueConstraint(
                fields=("enrollment", "lesson_key"),
                name="unique_lesson_completion_per_enrollment",
            ),
        ),
    ]
