# Generated by Django 4.2.7 on 2026-05-15 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_lesson_completion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdevelopmentplan",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("paused", "Paused"),
                    ("completed", "Completed"),
                ],
                default="active",
                max_length=16,
            ),
        ),
    ]
