# Generated by Django 4.2.7 on 2026-05-15 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_paused_dev_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdevelopmentplan",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Manager/admin who assigned this plan, if applicable.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_dev_plans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userdevelopmentplan",
            name="deadline",
            field=models.DateField(blank=True, null=True),
        ),
    ]
